apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysts

spec:
  serviceName: mysqldb
  replicas: 1

  selector:
    matchLabels:
      app: app-database

  template:
    metadata:
      labels:
        app: app-database

    spec:
      containers:
        - name: db-cont
          image: kavya318506/phpapp:dbimage

          ports:
            - containerPort: 3306

          envFrom:
            - secretRef:
                name: mysecret

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "250Mi"

          volumeMounts:
            - name: mypvc
              mountPath: /var/lib/mysql

  volumeClaimTemplates:
    - metadata:
        name: mypvc
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: gp2
        resources:
          requests:
            storage: 2Gi
